### ISSUE TITLE
Better error handling

### ISSUE THREAD

**Issue by nickdunn** [wearefriday/spectre_client#3]
If Spectre is misbehaving the client doesn't offer a way of recovering from erroneous responses.

We recently had a CI task bomb out when a screenshot comparison was failing because a baseline image had been corrupted.

```
rake aborted!
RestClient::ServiceUnavailable: 503 Service Unavailable
/var/lib/jenkins/jobs/cmb-pws-wraith/workspace/Rakefile:110:in `block in upload_screenshots_to_spectre'
```

Should this gem be handing the errors raised by RestClient, or should it be handled by scripts _using_ this gem?

**Comment by andypearson** [comment]
Ideally the client would either:

Rescue the error and continue (not sure that would be possible in this situation as the client is not responsible for the generation of the screenshot).

or: 

Rescue the error and then re-raise a more specific, obvious error (`SpectreClient::CorruptScreenshot`) for the user to handle themselves.

**Comment by Firefishy** [comment]
Unfortunately no longer being maintained. Please follow up with one of the active forks.
